#!/usr/bin/env bash
# DeepSeek-V4.1-Flash MXFP4 (dsv41 img, 4x, DSpark k=5, Engram-on-disk) — generated by `sm121 publish`. Run on rank 0; on each worker set
# NODE_RANK=<rank> and HEADLESS="--headless" (drop --host/--port).
set -euo pipefail

MODEL='deepseek-ai/DeepSeek-V4.1-Flash'
IMAGE='dsv41-flash:local'
MODEL_REVISION='dba1be0a40aa45a94ad051997016db3960a90277'   # pin: download + serve THIS revision (repo branches move)
MASTER_ADDR='192.168.200.15'   # rank-0 IB ip
NODE_RANK=0
HEADLESS=""

# --- fabric env (adjust per cluster) ------------------------------------
FABRIC_ENV=(
  -e NCCL_IB_HCA='rocep1s0f0,roceP2p1s0f0'
  -e NCCL_SOCKET_IFNAME='enp1s0f0np0'
  -e GLOO_SOCKET_IFNAME='enp1s0f0np0'
  -e NCCL_IB_DISABLE=0
  # NCCL_IB_GID_INDEX renumbers across reboots on DGX Spark —
  # detect the RoCE-v2 IPv4 GID per node, don't copy a stale number:
  # for i in $(seq 0 15); do grep -l RoCE* /sys/class/infiniband/$HCA/ports/1/gid_attrs/types/$i 2>/dev/null && echo $i; done
)

exec docker run -d --name pub-deepseek-ai-DeepSeek-V4.1-Flash --gpus all --ipc=host --network host \
  --shm-size 32gb \
  -v ~/.cache/huggingface:/root/.cache/huggingface \
  "${FABRIC_ENV[@]}" \
  -e 'DSV41_ENGRAM_DIR=/engram-local' \
  -e 'DSV41_ENGRAM_DISK=1' \
  -e 'DSV41_ENGRAM_DISK_CHUNK=16' \
  -e 'DSV41_ENGRAM_DISK_THREADS=32' \
  -e 'DSV41_ENGRAM_LOCAL=1' \
  -e 'FLASHINFER_CUDA_ARCH_LIST=12.1a' \
  -e 'HF_HUB_OFFLINE=1' \
  -e 'MAX_JOBS=2' \
  -e 'OMP_NUM_THREADS=2' \
  -e 'PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True' \
  -e 'TORCH_CUDA_ARCH_LIST=12.1a' \
  -e 'VLLM_ENGINE_READY_TIMEOUT_S=3600' \
  -e 'VLLM_HAS_FLASHINFER_CUBIN=1' \
  -e 'VLLM_USE_BREAKABLE_CUDAGRAPH=1' \
  -e 'VLLM_USE_RUST_FRONTEND=0' \
  "$IMAGE" \
  --model "$MODEL" --revision "$MODEL_REVISION" \
  --tensor-parallel-size 4 --nnodes 4 --node-rank "$NODE_RANK" --master-addr "$MASTER_ADDR" --master-port 25000 \
  '--served-model-name' \
  'deepseek-v4-flash' \
  '--trust-remote-code' \
  '--distributed-executor-backend' \
  'mp' \
  '--gpu-memory-utilization' \
  '0.85' \
  '--max-model-len' \
  '524288' \
  '--max-num-seqs' \
  '8' \
  '--max-num-batched-tokens' \
  '8192' \
  '--block-size' \
  '128' \
  '--compilation-config' \
  '{"cudagraph_mode":"FULL_AND_PIECEWISE","cudagraph_capture_sizes":[5,6,10,12,15,18,20,24,25,30,35,36,40,42,48]}' \
  '--speculative-config' \
  '{"method":"dspark","num_speculative_tokens":5,"draft_sample_method":"probabilistic","rejection_sample_method":"block","enable_adaptive_verification":false}' \
  '--tool-call-parser' \
  'deepseek_v41' \
  '--enable-auto-tool-choice' \
  '--reasoning-parser' \
  'deepseek_v41' \
  '--default-chat-template-kwargs' \
  '{"thinking": true, "reasoning_effort": "max"}' \
  ${HEADLESS:+$HEADLESS} \
  --host 0.0.0.0 --port 30000
